services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql+psycopg://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      OFF_BASE_URL: https://it.openfoodfacts.org
      FDC_API_KEY: ${FDC_API_KEY:-}
      PLANNER_MODE: heuristic
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - node_modules_web:/app/node_modules

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5050:80"
    depends_on:
      - db

  importer:
    build: ./importer
    environment:
      DATABASE_URL: postgresql+psycopg://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      OFF_BASE_URL: https://it.openfoodfacts.org
      FDC_API_KEY: ${FDC_API_KEY:-}
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [ "python", "/app/run.py" ]
    profiles: [ "manual" ] # non parte con `up` se non attivi il profilo

volumes:
  db_data:
  pgadmin_data:
  node_modules_web:
